USE [master]
GO

/****** Object:  Database [Automation]    Script Date: 12/28/2020 10:41:35 AM ******/
CREATE DATABASE [Automation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Automation', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Automation1.mdf' , SIZE = 3175616KB , MAXSIZE = UNLIMITED, FILEGROWTH = 15%)
 LOG ON 
( NAME = N'Automation_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Automation1_log.ldf' , SIZE = 4199808KB , MAXSIZE = 2048GB , FILEGROWTH = 15%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Automation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Automation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Automation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Automation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Automation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Automation] SET ARITHABORT OFF 
GO

ALTER DATABASE [Automation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Automation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Automation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Automation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Automation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Automation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Automation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Automation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Automation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Automation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Automation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Automation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Automation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Automation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Automation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Automation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Automation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Automation] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Automation] SET  MULTI_USER 
GO

ALTER DATABASE [Automation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Automation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Automation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Automation] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Automation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Automation] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Automation] SET QUERY_STORE = OFF
GO

USE [Automation]
GO

EXEC [Automation].sys.sp_addextendedproperty @name=N'DB_Function', @value=N'repository for Sys Admin operations and management data ' 
GO

USE [master]
GO

ALTER DATABASE [Automation] SET  READ_WRITE 
GO


